import * as Joi from 'joi'
import * as fs from 'fs'

export default Joi.object({
  npm_package_version: Joi.string().required(),
  SERVICE_HOST: Joi.string().hostname().required(),
  SERVICE_PORT: Joi.number().port().required(),
  LOG_LEVEL: Joi.string().allow('error', 'warn', 'log', 'verbose', 'debug').default('log'),
  LOG_STAT_INTERVAL_SECONDS: Joi.number().integer().min(0).default(60),
  DB_HOST: Joi.string().required(),
  DB_PORT: Joi.number().required(),
  DB_NAME: Joi.string().required(),
  DB_USERNAME: Joi.string().required(),
  DB_PASSWORD: Joi.string().required(),
  DB_SCHEMA: Joi.string().required(),
  PAY_LINK_BACK_END_URL: Joi.string().uri({ scheme: ['http', 'https'] }).required(),
  PAY_LINK_FRONT_END_URL: Joi.string().uri({ scheme: ['http', 'https'] }).required(),
  PAY_LINK_TERMINAL_ID: Joi.string().min(1).max(50).required(),
  PAY_LINK_PRIVATE_KEY: Joi.string().required(),
  PAY_LINK_SESSION_EXPIRATION_SECONDS: Joi.number().integer().min(0).default(180),
  POST_TRANSACTION_SERVICE_URL: Joi.string().uri({ scheme: ['http', 'https'] }).required(),
  POST_TRANSACTION_CERTIFICATE_PFX: Joi.string().required().custom(value => fs.readFileSync(value)),
  POST_TRANSACTION_CERTIFICATE_PASSWORD: Joi.string().required(),
  POST_TRANSACTION_BASIC_USERNAME: Joi.string().required(),
  POST_TRANSACTION_BASIC_PASSWORD: Joi.string().required(),
  POST_TRANSACTION_TERMINAL_ID: Joi.number().integer().required(),
  PAYMENT_STATUS_UPDATE_MIN_INTERVAL_SECONDS: Joi.number().integer().min(1).default(10),
  PAYMENT_STATUS_UPDATE_MAX_INTERVAL_SECONDS: Joi.number().integer().min(Joi.ref('PAYMENT_STATUS_UPDATE_MIN_INTERVAL_SECONDS')).default(60 * 60 * 24),
  PAYMENT_STATUS_UPDATE_CONCURRENCY: Joi.number().integer().min(1).default(5),
  PAYMENT_STATUS_UPDATE_GIVE_UP_AFTER_DAYS: Joi.number().integer().min(1).default(null),
  AUTH_SERVICE_URL: Joi.string().uri({ scheme: ['http', 'https'] }).required(),
  AUTH_CLIENT_ID: Joi.string().required(),
  AUTH_CLIENT_SECRET: Joi.string().required(),
  NOTIFICATION_MIN_INTERVAL_SECONDS: Joi.number().integer().min(1).default(10),
  NOTIFICATION_MAX_INTERVAL_SECONDS: Joi.number().integer().min(Joi.ref('NOTIFICATION_MIN_INTERVAL_SECONDS')).default(60 * 60 * 24),
  NOTIFICATION_CONCURRENCY: Joi.number().integer().min(1).default(5),
  NOTIFICATION_GIVE_UP_AFTER_DAYS: Joi.number().integer().min(1).default(30),
  NOTIFICATION_ON_PAYMENT_CHANGE: Joi.boolean().default(false),
  NOTIFICATION_ON_PAYMENT_REFUND: Joi.boolean().default(false),
  SSE_EXPIRATION_SECONDS: Joi.number().integer().min(0).default(60 * 15),
  EMAIL_HOST: Joi.string().required(),
  EMAIL_PORT: Joi.number().required(),
  EMAIL_USERNAME: Joi.string().required(),
  EMAIL_PASSWORD: Joi.string().required(),
  EMAIL_COMPANY_NAME: Joi.string().required(),
  EMAIL_COMPANY_PHONE: Joi.string().required(),
})